### ISSUE TITLE
Remove html tag and use a transformers

### ISSUE THREAD

**Issue by AxelBriche** [Dashibase/lotion#11]
Having html tags here is not good:

<img width="648" alt="CleanShot 2022-07-29 at 14 38 39@2x" src="https://user-images.githubusercontent.com/1295251/181761553-f3184318-f79d-4bca-9165-976eced17e6b.png">

This data should be in a format that can be stored in a database.
And as a developer, I don't want store html tags inside my database, only markdown or cleaned data.

Instead of:
```
{
    type: "TEXT",
    details: {
      value: '<p>5. <strong>Bold</strong> and <em>italicize</em> using markdown e.g. *italic* or **bold**</p>'
    },
  }
```

I want provide:
```
{
    "type": "TEXT",
    "details": {
      "value": "5. **Bold** and *italicize* using markdown e.g. *italic* or **bold**"
    }
}
```

And transform it if needed for the editor.

**Comment by greentfrapp** [comment]
This should be fixed with the latest version!
