### ISSUE TITLE
Deleting all blocks leaves the editor in a state where new blocks can't be added

### ISSUE THREAD

**Issue by allanw** [Dashibase/lotion#22]
I was playing around with the demo at https://lotion.dashibase.com/ and noticed that if I delete all the blocks (I started at the bottom and moved upwards, leaving just the main heading remaining), I get into a state where I can't seem to add any new blocks. At this point, I don't see a tooltip to add a new block and the '/' shortcut doesn't popup the menu to convert a block to a particular type.

**Comment by greentfrapp** [comment]
Thanks @allanw for reporting this! 🧴
Just fixed this in the latest commit dc4cadd so that there will always be at least one text block in the editor.
