### ISSUE TITLE
Component search improvements

### ISSUE THREAD

**Issue by ivteplo** [Dashibase/lotion#3]
Typing `/heading` shows two variants: `Heading 1` and `Heading 2`.

However, typing `/h1` to quickly access `Heading 1` doesn't work. The same is for `/h2`.

Additionally, if I insert spaces, just like `/heading 1`, the search ignores the space, tries to look for `heading1`, and says that nothing was found. And backspacing three times after that leaves `/headi` in the search box instead of `/headin`.

**Comment by alfredlua** [comment]
Good ones!

We will look into that. Or you are interested, feel free to contribute! 😊 

Adding this for reference:

![image](https://user-images.githubusercontent.com/4110257/181439845-432f970c-d0ee-4b6e-b00e-204bf279a0c9.png)

**Comment by ivteplo** [comment]
I'll try to fix these

**Comment by ivteplo** [comment]
Just found another bug: if the block menu is closed manually (by using `Esc` or other methods), the previous component search query doesn't get cleared

**Comment by ivteplo** [comment]
The same bug was when clicking outside the menu

**Comment by ivteplo** [comment]
Merged to main
