### ISSUE TITLE
Merging empty heading block into another causes unexpected behaviour

### ISSUE THREAD

**Issue by vvidday** [Dashibase/lotion#35]
merging an empty heading block into another results in "undefined" being added to the block being merged into. 
<details>
<summary>video</summary>

![mergeintoheading-before](https://user-images.githubusercontent.com/45852430/182515128-8d34d2a4-4a45-40c7-800e-32213d7efc24.gif)
</details>

**Comment by greentfrapp** [comment]
Fixed by #36
