### ISSUE TITLE
Caret moves down when trying to add multiple blocks

### ISSUE THREAD

**Issue by lyqht** [Dashibase/lotion#41]
## Description

In Notion, when you click on the "+" button next to the block, you will see a context menu to choose the custom block that you want to add to your document, so there isn't a behavior of repeatedly clicking on the "+" button.

However, in **Lotion**, right now, when we click on the "+" button repeatedly, the caret is immediately moved to the new block. This results the user to leave where they are previously. While this logic does seem to follow how Notion implements it, it is not ideal for users that just want to add multiple placeholder blocks.

## Screenshots
![scroll_position_shifts_down_when_adding_items](https://user-images.githubusercontent.com/35736525/182608197-fa2bb518-61df-4f53-b1c2-f7d344781e06.gif)

**Comment by greentfrapp** [comment]
@lyqht interesting point - any suggestions for how you would prefer the caret to behave?

**Comment by lyqht** [comment]
Previously this behavior looked funny to me since I wanted to stay at the same spot while adding more blocks. But now that I think about this issue again, I think it's actually fine.
