### ISSUE TITLE
Nuxt 3 style error

### ISSUE THREAD

**Issue by patrickphat** [Dashibase/lotion#70]
**Describe the bug**
I try to use Nuxt 3 but it is not totally rendered

**To Reproduce**
1. Follow 
2. Copy the example 
```
<template>
  <Lotion :page="page" />
</template>
<script setup lang="ts">
import { ref } from 'vue'
import { v4 as uuidv4 } from 'uuid'
import { Lotion, registerBlock } from '@dashibase/lotion'

const page = ref({
  name: '🧴 Lotion',
  blocks:[{
    id: uuidv4(),
    type: 'TEXT',
    details: {
      value: 'Hello, World!'
    },
  }],
})
</script>
```
3. Paste to pages/index.vue

**Expected behavior**
A beautifully rendered Lotion editor

**Screenshots**
<img width="289" alt="image" src="https://user-images.githubusercontent.com/45748186/194601102-a8e4423c-4cc5-45bb-bf31-6cd8d931b08c.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by patrickphat** [comment]
No one help. closed.

**Comment by hendrikbl** [comment]
@patrickphat i know it's been a while, but did you get it to work with nuxt 3? I'm facing the same issue.
